# Generated by Django 4.2.7 on 2023-11-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem_posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=30)),
                ('phonenumber', models.IntegerField(blank=True, max_length=11, null=True)),
                ('problem', models.TextField(max_length=300)),
                ('date_created', models.DateTimeField()),
            ],
        ),
    ]
