# Generated by Django 4.2.7 on 2023-11-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem_posts',
            name='phonenumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
