# Generated by Django 4.2.7 on 2023-11-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_alter_problem_posts_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem_posts',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
